name: openwrt
on: [push]
jobs:
  openwrt:
    runs-on: ubuntu-18.04
    steps:
      - name: get code
        uses: actions/checkout@v2
      - run: cd ${{ github.workspace }}
      - run: sudo apt-get update
      - run: sudo apt-get install -y --fix-missing build-essential asciidoc binutils bzip2 curl gawk gettext git libncurses5-dev libz-dev patch python3.5 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf
      - name: download
        run: make -j$(nproc) download V=s
      - name: make
        run: make -j3 V=s
      - name: export
        uses: actions/upload-artifact@master
        with:
          name: outfile-bin
          path: ./bin
