name: openwrt
on: [push]
jobs:
  openwrt:
    runs-on: ubuntu-18.04
    steps:
      - name: get code
        uses: actions/checkout@v2 
      - run: cd ${{ github.workspace }}
      - run: sudo apt-get update
      - run: sudo apt-get install -y uild-essential ccache ecj fastjar file g++ gawk gettext git java-propose-classpath libelf-dev libncurses5-dev libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget python3-distutils python3-setuptools python3-dev rsync subversion swig time xsltproc zlib1g-dev 
      - name: download
        run: make -j$(nproc) download V=s
      - name: export
        uses: actions/upload-artifact@master
        with:
          name: outfile-dl-${{ github.event.inputs.devtype }}
          path: ./dl
