name: openwrt
on: [push]
jobs:
  openwrt:
    runs-on: ubuntu-18.04
    steps:
      - name: get code
        uses: actions/checkout@v2 
      - run: cd ${{ github.workspace }}
      - run: sudo apt-get update
      - run: sudo apt-get -y install gcc g++ libcap2-bin libcap-bin  binutils bzip2 flex python perl make grep unzip gawk subversion libz-dev libc-dev git vim libncurses5-dev wget sudo curl git bison python python3
      - name: download
        run: make -j$(nproc) download V=s
      - name: export
        uses: actions/upload-artifact@master
        with:
          name: outfile-dl-${{ github.event.inputs.devtype }}
          path: ./dl
