name: dl
on: [push]
jobs:
  dl:
    runs-on: ubuntu:18.04
    steps:
      - name: a
        uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: sudo apt-get -y install ethtool build-essential asciidoc binutils bzip2 curl gawk gettext git libncurses5-dev libz-dev patch python3.5 python2.7 unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf         
      - run: cd ${{ github.workspace }}
      - name: driver r8168
        run: |
          cd package
          git clone https://github.com/zeruns/openwrt-r8168 
          cd ${{ github.workspace }}
          cat >> .config <<EOF
          CONFIG_PACKAGE_kmod-r8168=y
          EOF
      - name: download dl
        run: make -j$(nproc) download V=99
      - name: export dl
        uses: actions/upload-artifact@master
        with:
          name: outfile-dl
          path: ./dl
