name: openwrt
on: [push]
jobs:
  openwrt:
    runs-on: ubuntu-18.04
    steps:
      - run: echo "核心数$(nproc)"
      - name: 获取代码
        uses: actions/checkout@v2
      - run: cd ${{ github.workspace }}
      - name: 更新包
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: 获取网卡驱动
        run: |
          cd package
          git clone https://github.com/zeruns/openwrt-r8168 
          cd ${{ github.workspace }}
          cat >> .config <<EOF
          CONFIG_PACKAGE_kmod-r8168=y
          EOF
      - name: 下载dl库
        run: sh ./download
      - name: 导出dl库
        uses: actions/upload-artifact@master
        with:
          name: outfile-dl-${{ github.event.inputs.devtype }}
          path: ./dl
      - name: 编译
        run: sh ./build
      - name: 输出文件
        uses: actions/upload-artifact@master
        with:
          name: outfile-${{ github.event.inputs.devtype }}
          path: ./trunk/bin
      - run: echo "状态${{ job.status }}"
  dl:
    runs-on: ubuntu-18.04
    steps:
      - name: 获取代码
        uses: actions/checkout@v2
      - run: cd ${{ github.workspace }}
      - name: 更新包
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: 下载dl库
        run: sh ./download
      - name: 导出dl库
        uses: actions/upload-artifact@master
        with:
          name: outfile-dl-${{ github.event.inputs.devtype }}
          path: ./dl
