name: openwrt
on: [push]
jobs:
  openwrt:
    runs-on: debian:8.0
    steps:
      - run: echo "核心数$(nproc)"
      - name: 获取代码
        uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: sudo apt-get -y install ethtool build-essential asciidoc binutils bzip2 curl gawk gettext git libncurses5-dev libz-dev patch python3.5 python2.7 unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf         
      - run: cd ${{ github.workspace }}
      - name: 更新包
        run: |
          ./scripts/feeds clean
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: 获取网卡驱动
        run: |
          cd package
          git clone https://github.com/zeruns/openwrt-r8168 
          cd ${{ github.workspace }}
          cat >> .config <<EOF
          CONFIG_PACKAGE_kmod-r8168=y
          EOF
      - name: 下载dl库
        run: sh ./download
      - name: 导出dl库
        uses: actions/upload-artifact@master
        with:
          name: outfile-dl-${{ github.event.inputs.devtype }}
          path: ./dl
      - name: 编译
        run: sh ./build
      - name: 输出文件
        uses: actions/upload-artifact@master
        with:
          name: outfile-${{ github.event.inputs.devtype }}
          path: ./trunk/bin
